### ISSUE TITLE
OneCycleWaveform - Pulse isn't doing anything

### ISSUE THREAD

**Issue by gonzalom8** [ryukau/UhhyouWebSynthesizers#5] opened 2024-03-02 21:13 UTC
Moving "Sine-Saw-Pulse" parameter from Shape, is doing sine and saw but not the pulse waveform.

**Comment by ryukau** [comment] 2024-03-02 22:25
Thanks for reporting. The issue is fixed in 5a5e680.

In default, the pulse is 1 octave higher than sine-saw. To makes the pulse 1 octave lower, `Mirror/Repeat` must be set to 1.0.

**Closed by ryukau** 2024-03-02 22:25 UTC
